ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER BANK_CORE IDENTIFIED BY bank123
    DEFAULT TABLESPACE USERS
    QUOTA UNLIMITED ON USERS;

CREATE USER APP_CONSISTENCIA IDENTIFIED BY app123
    DEFAULT TABLESPACE USERS
    QUOTA UNLIMITED ON USERS;

CREATE USER APP_READONLY IDENTIFIED BY readonly123;
CREATE USER APP_READWRITE IDENTIFIED BY rw123;
CREATE USER APP_RESTRICTED IDENTIFIED BY restricted123;

GRANT CONNECT, RESOURCE TO BANK_CORE;
GRANT CONNECT, RESOURCE TO APP_CONSISTENCIA;
GRANT CONNECT TO APP_READONLY;
GRANT CONNECT TO APP_READWRITE;
GRANT CONNECT TO APP_RESTRICTED;

ALTER USER BANK_CORE QUOTA UNLIMITED ON USERS;
ALTER USER APP_CONSISTENCIA QUOTA UNLIMITED ON USERS;
