ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = BANK_CORE;

CREATE OR REPLACE PACKAGE PK_SCORE AS
    PROCEDURE CALCULAR_SCORE_INTERNO(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_SCORE;
/

CREATE OR REPLACE PACKAGE BODY PK_SCORE AS
    PROCEDURE CALCULAR_SCORE_INTERNO(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_SCORE NUMBER;
        V_SCORE_MINIMO CONSTANT NUMBER := 600;
    BEGIN
        SELECT NVL(SCORE_INTERNO, 0) INTO V_SCORE
        FROM CLIENTES WHERE COD_CLI = P_COD_CLI;

        IF V_SCORE >= V_SCORE_MINIMO THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Score interno aprovado';
        ELSE
            P_RESULTADO_NEGOCIO := 'REPROVADO';
            P_MENSAGEM := 'Score interno abaixo do minimo';
        END IF;

        P_PAYLOAD_JSON := '{"score":' || V_SCORE || ',"scoreMinimo":' || V_SCORE_MINIMO || '}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Cliente nao encontrado';
                P_PAYLOAD_JSON := '{"erro":"Cliente nao encontrado"}';
            WHEN OTHERS THEN
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao calcular score: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END CALCULAR_SCORE_INTERNO;
END PK_SCORE;
/

CREATE OR REPLACE PACKAGE PK_BACEN AS
    PROCEDURE CONSULTAR_SCR(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_BACEN;
/

CREATE OR REPLACE PACKAGE BODY PK_BACEN AS
    PROCEDURE CONSULTAR_SCR(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_OPERACOES_ATIVAS NUMBER := 0;
        V_VALOR_TOTAL_RISCO NUMBER := 0;
    BEGIN
        SELECT COUNT(*), NVL(SUM(VALOR_TOTAL), 0)
        INTO V_OPERACOES_ATIVAS, V_VALOR_TOTAL_RISCO
        FROM CONTRATOS
        WHERE COD_CLI = P_COD_CLI AND STATUS IN ('ATIVO', 'VENCIDO');

        IF V_VALOR_TOTAL_RISCO < 100000 THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'SCR sem restricoes impeditivas';
        ELSE
            P_RESULTADO_NEGOCIO := 'ALERTA';
            P_MENSAGEM := 'Valor total em risco elevado';
        END IF;

        P_PAYLOAD_JSON := '{"operacoesAtivas":' || V_OPERACOES_ATIVAS ||
                          ',"valorTotalRisco":' || V_VALOR_TOTAL_RISCO || '}';

        EXCEPTION
            WHEN OTHERS THEN
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao consultar SCR: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END CONSULTAR_SCR;
END PK_BACEN;
/

CREATE OR REPLACE PACKAGE PK_RENDA AS
    PROCEDURE VALIDAR_RENDA(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_RENDA;
/

CREATE OR REPLACE PACKAGE BODY PK_RENDA AS
    PROCEDURE VALIDAR_RENDA(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_RENDA NUMBER;
    BEGIN
        SELECT NVL(RENDA_COMPROVADA, 0) INTO V_RENDA
        FROM CLIENTES WHERE COD_CLI = P_COD_CLI;

        IF V_RENDA >= 1500 THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Renda comprovada suficiente';
        ELSIF V_RENDA > 0 THEN
            P_RESULTADO_NEGOCIO := 'ALERTA';
            P_MENSAGEM := 'Renda comprovada abaixo do ideal';
        ELSE
            P_RESULTADO_NEGOCIO := 'REPROVADO';
            P_MENSAGEM := 'Renda nao comprovada';
        END IF;

        P_PAYLOAD_JSON := '{"rendaComprovada":' || V_RENDA || '}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Cliente nao encontrado para validacao de renda';
                P_PAYLOAD_JSON := '{"erro":"Cliente nao encontrado"}';
            WHEN OTHERS THEN
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao validar renda: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END VALIDAR_RENDA;
END PK_RENDA;
/

CREATE OR REPLACE PACKAGE PK_CREDITO AS
    PROCEDURE ANALISAR_CAPACIDADE(
        P_COD_CLI IN NUMBER,
        P_VALOR_SOLICITADO IN NUMBER,
        P_QTD_PARCELAS IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_CREDITO;
/

CREATE OR REPLACE PACKAGE BODY PK_CREDITO AS
    PROCEDURE ANALISAR_CAPACIDADE(
        P_COD_CLI IN NUMBER,
        P_VALOR_SOLICITADO IN NUMBER,
        P_QTD_PARCELAS IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_RENDA NUMBER;
        V_PARCELA_MENSAL NUMBER;
        V_COMPROMETIMENTO NUMBER;
    BEGIN
        SELECT NVL(RENDA_COMPROVADA, 0) INTO V_RENDA
        FROM CLIENTES WHERE COD_CLI = P_COD_CLI;

        V_PARCELA_MENSAL := P_VALOR_SOLICITADO / P_QTD_PARCELAS;
        V_COMPROMETIMENTO := (V_PARCELA_MENSAL / NULLIF(V_RENDA, 0)) * 100;

        IF V_COMPROMETIMENTO <= 30 THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Capacidade de pagamento adequada';
        ELSIF V_COMPROMETIMENTO <= 50 THEN
            P_RESULTADO_NEGOCIO := 'ALERTA';
            P_MENSAGEM := 'Comprometimento de renda elevado';
        ELSE
            P_RESULTADO_NEGOCIO := 'REPROVADO';
            P_MENSAGEM := 'Comprometimento de renda acima do limite';
        END IF;

        P_PAYLOAD_JSON := '{"renda":' || V_RENDA ||
                          ',"parcelaMensal":' || V_PARCELA_MENSAL ||
                          ',"comprometimento":' || ROUND(V_COMPROMETIMENTO, 2) || '}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Cliente nao encontrado';
                P_PAYLOAD_JSON := '{"erro":"Cliente nao encontrado"}';
            WHEN OTHERS THEN
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao analisar capacidade: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END ANALISAR_CAPACIDADE;
END PK_CREDITO;
/

CREATE OR REPLACE PACKAGE PK_PROPOSTA AS
    PROCEDURE GERAR_PROPOSTA(
        P_COD_CLI IN NUMBER,
        P_VALOR IN NUMBER,
        P_PARCELAS IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_PROPOSTA;
/

CREATE OR REPLACE PACKAGE BODY PK_PROPOSTA AS
    PROCEDURE GERAR_PROPOSTA(
        P_COD_CLI IN NUMBER,
        P_VALOR IN NUMBER,
        P_PARCELAS IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_TAXA NUMBER;
        V_CET NUMBER;
        V_PROPOSTA_ID NUMBER;
    BEGIN
        V_TAXA := ROUND(DBMS_RANDOM.VALUE(1.5, 5.0), 4);
        V_CET := ROUND(V_TAXA * 1.2, 4);

        INSERT INTO PROPOSTAS_CREDITO (
            COD_CLI, VALOR_SOLICITADO, QTD_PARCELAS, TAXA_MENSAL, CET, STATUS
        ) VALUES (
            P_COD_CLI, P_VALOR, P_PARCELAS, V_TAXA, V_CET, 'PENDENTE'
        ) RETURNING PROPOSTA_ID INTO V_PROPOSTA_ID;

        COMMIT;

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Proposta comercial gerada com sucesso';
        P_PAYLOAD_JSON := '{"propostaId":' || V_PROPOSTA_ID ||
                          ',"taxaMensal":' || V_TAXA ||
                          ',"cet":' || V_CET || '}';

        EXCEPTION
            WHEN OTHERS THEN
                ROLLBACK;
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao gerar proposta: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END GERAR_PROPOSTA;
END PK_PROPOSTA;
/

CREATE OR REPLACE PACKAGE PK_ONBOARDING AS
    PROCEDURE VALIDAR_DOCUMENTO_RECEITA(
        P_CPF_CNPJ IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE VERIFICAR_LISTAS_RESTRITIVAS(
        P_CPF_CNPJ IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE VALIDAR_BIOMETRIA_FACE(
        P_BIOMETRIA_HASH IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE CONSULTAR_RESTRICOES_FINANCEIRAS(
        P_CPF_CNPJ IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE CRIAR_CONTA_CORE_BANCARIO(
        P_CPF_CNPJ IN VARCHAR2,
        P_CANAL_ORIGEM IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_ONBOARDING;
/

CREATE OR REPLACE PACKAGE BODY PK_ONBOARDING AS
    PROCEDURE VALIDAR_DOCUMENTO_RECEITA(
        P_CPF_CNPJ IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_EXISTS NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_EXISTS FROM CLIENTES WHERE CPF_CNPJ = P_CPF_CNPJ;

        IF LENGTH(P_CPF_CNPJ) IN (11, 14) THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Documento valido na Receita Federal';
        ELSE
            P_RESULTADO_NEGOCIO := 'REPROVADO';
            P_MENSAGEM := 'Documento invalido';
        END IF;

        P_PAYLOAD_JSON := '{"documentoValidado":true,"cpfCnpj":"' || P_CPF_CNPJ || '"}';
    END VALIDAR_DOCUMENTO_RECEITA;

    PROCEDURE VERIFICAR_LISTAS_RESTRITIVAS(
        P_CPF_CNPJ IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Nao consta em listas restritivas';
        P_PAYLOAD_JSON := '{"listasRestritivas":0}';
    END VERIFICAR_LISTAS_RESTRITIVAS;

    PROCEDURE VALIDAR_BIOMETRIA_FACE(
        P_BIOMETRIA_HASH IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        IF P_BIOMETRIA_HASH IS NOT NULL AND LENGTH(P_BIOMETRIA_HASH) > 10 THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Biometria facial validada com sucesso';
        ELSE
            P_RESULTADO_NEGOCIO := 'ALERTA';
            P_MENSAGEM := 'Biometria nao informada para validacao';
        END IF;

        P_PAYLOAD_JSON := '{"biometriaValidada":true}';
    END VALIDAR_BIOMETRIA_FACE;

    PROCEDURE CONSULTAR_RESTRICOES_FINANCEIRAS(
        P_CPF_CNPJ IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_EXISTS NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_EXISTS FROM CLIENTES WHERE CPF_CNPJ = P_CPF_CNPJ;

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Sem restricoes financeiras impeditivas';
        P_PAYLOAD_JSON := '{"restricoesFinanceiras":0}';
    END CONSULTAR_RESTRICOES_FINANCEIRAS;

    PROCEDURE CRIAR_CONTA_CORE_BANCARIO(
        P_CPF_CNPJ IN VARCHAR2,
        P_CANAL_ORIGEM IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_COD_CLI NUMBER;
        V_AGENCIA VARCHAR2(10);
        V_CONTA VARCHAR2(20);
    BEGIN
        SELECT COD_CLI INTO V_COD_CLI FROM CLIENTES WHERE CPF_CNPJ = P_CPF_CNPJ;

        V_AGENCIA := '0001';
        V_CONTA := TO_CHAR(DBMS_RANDOM.VALUE(10000, 99999)) || '-' || TO_CHAR(DBMS_RANDOM.VALUE(0, 9));

        INSERT INTO CONTAS (AGENCIA, CONTA, COD_CLI, SALDO_DISPONIVEL, STATUS, LIMITE_PIX_DIARIO)
        VALUES (V_AGENCIA, V_CONTA, V_COD_CLI, 0, 'ATIVA', 5000);

        COMMIT;

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Conta criada com sucesso no core bancario';
        P_PAYLOAD_JSON := '{"agencia":"' || V_AGENCIA || '","conta":"' || V_CONTA || '"}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                ROLLBACK;
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Cliente nao encontrado';
                P_PAYLOAD_JSON := '{"erro":"Cliente nao encontrado"}';
            WHEN OTHERS THEN
                ROLLBACK;
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao criar conta: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END CRIAR_CONTA_CORE_BANCARIO;
END PK_ONBOARDING;
/

CREATE OR REPLACE PACKAGE PK_PIX AS
    PROCEDURE VALIDAR_CHAVE_PIX(
        P_CHAVE_DESTINO IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE VERIFICAR_SALDO_DISPONIVEL(
        P_AGENCIA IN VARCHAR2,
        P_CONTA IN VARCHAR2,
        P_VALOR IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE CHECAR_LIMITES_OPERACIONAIS(
        P_AGENCIA IN VARCHAR2,
        P_CONTA IN VARCHAR2,
        P_VALOR IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE ANALISAR_PADRAO_FRAUDE(
        P_AGENCIA_ORIGEM IN VARCHAR2,
        P_CONTA_ORIGEM IN VARCHAR2,
        P_CHAVE_DESTINO IN VARCHAR2,
        P_VALOR IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE EXECUTAR_DEBITO_CREDITO_CORE(
        P_AGENCIA_ORIGEM IN VARCHAR2,
        P_CONTA_ORIGEM IN VARCHAR2,
        P_CHAVE_DESTINO IN VARCHAR2,
        P_VALOR IN NUMBER,
        P_ID_SOLICITACAO IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_PIX;
/

CREATE OR REPLACE PACKAGE BODY PK_PIX AS
    PROCEDURE VALIDAR_CHAVE_PIX(
        P_CHAVE_DESTINO IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_EXISTS NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_EXISTS FROM CHAVES_PIX WHERE CHAVE = P_CHAVE_DESTINO AND STATUS = 'ATIVA';

        IF V_EXISTS > 0 THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Chave PIX valida e ativa';
            P_PAYLOAD_JSON := '{"chaveValida":true}';
        ELSE
            P_RESULTADO_NEGOCIO := 'REPROVADO';
            P_MENSAGEM := 'Chave PIX nao encontrada ou inativa';
            P_PAYLOAD_JSON := '{"chaveValida":false}';
        END IF;
    END VALIDAR_CHAVE_PIX;

    PROCEDURE VERIFICAR_SALDO_DISPONIVEL(
        P_AGENCIA IN VARCHAR2,
        P_CONTA IN VARCHAR2,
        P_VALOR IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_SALDO NUMBER;
    BEGIN
        SELECT NVL(SALDO_DISPONIVEL, 0) INTO V_SALDO
        FROM CONTAS WHERE AGENCIA = P_AGENCIA AND CONTA = P_CONTA;

        IF V_SALDO >= P_VALOR THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Saldo disponivel suficiente';
        ELSE
            P_RESULTADO_NEGOCIO := 'REPROVADO';
            P_MENSAGEM := 'Saldo insuficiente';
        END IF;

        P_PAYLOAD_JSON := '{"saldoDisponivel":' || V_SALDO || '}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Conta nao encontrada';
                P_PAYLOAD_JSON := '{"erro":"Conta nao encontrada"}';
    END VERIFICAR_SALDO_DISPONIVEL;

    PROCEDURE CHECAR_LIMITES_OPERACIONAIS(
        P_AGENCIA IN VARCHAR2,
        P_CONTA IN VARCHAR2,
        P_VALOR IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_LIMITE_PIX NUMBER;
    BEGIN
        SELECT NVL(LIMITE_PIX_DIARIO, 0) INTO V_LIMITE_PIX
        FROM CONTAS WHERE AGENCIA = P_AGENCIA AND CONTA = P_CONTA;

        IF P_VALOR <= V_LIMITE_PIX THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Limite operacional disponivel';
        ELSE
            P_RESULTADO_NEGOCIO := 'REPROVADO';
            P_MENSAGEM := 'Valor excede limite PIX diario';
        END IF;

        P_PAYLOAD_JSON := '{"limitePixDiario":' || V_LIMITE_PIX || '}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Conta nao encontrada';
                P_PAYLOAD_JSON := '{"erro":"Conta nao encontrada"}';
    END CHECAR_LIMITES_OPERACIONAIS;

    PROCEDURE ANALISAR_PADRAO_FRAUDE(
        P_AGENCIA_ORIGEM IN VARCHAR2,
        P_CONTA_ORIGEM IN VARCHAR2,
        P_CHAVE_DESTINO IN VARCHAR2,
        P_VALOR IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        IF P_VALOR > 50000 THEN
            P_RESULTADO_NEGOCIO := 'ALERTA';
            P_MENSAGEM := 'Valor alto, necessidade de aprovacao adicional';
        ELSE
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Sem indicativo de fraude';
        END IF;

        P_PAYLOAD_JSON := '{"nivelRisco":"BAIXO","scoreFraude":12}';
    END ANALISAR_PADRAO_FRAUDE;

    PROCEDURE EXECUTAR_DEBITO_CREDITO_CORE(
        P_AGENCIA_ORIGEM IN VARCHAR2,
        P_CONTA_ORIGEM IN VARCHAR2,
        P_CHAVE_DESTINO IN VARCHAR2,
        P_VALOR IN NUMBER,
        P_ID_SOLICITACAO IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        UPDATE CONTAS SET SALDO_DISPONIVEL = SALDO_DISPONIVEL - P_VALOR
        WHERE AGENCIA = P_AGENCIA_ORIGEM AND CONTA = P_CONTA_ORIGEM;

        INSERT INTO OPERACOES_PIX (ID_OPERACAO, AGENCIA_ORIGEM, CONTA_ORIGEM, CHAVE_DESTINO, VALOR, STATUS)
        VALUES (P_ID_SOLICITACAO, P_AGENCIA_ORIGEM, P_CONTA_ORIGEM, P_CHAVE_DESTINO, P_VALOR, 'EXECUTADO');

        COMMIT;

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'PIX executado com sucesso';
        P_PAYLOAD_JSON := '{"idOperacao":"' || P_ID_SOLICITACAO || '","status":"EXECUTADO"}';

        EXCEPTION
            WHEN OTHERS THEN
                ROLLBACK;
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao executar PIX: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END EXECUTAR_DEBITO_CREDITO_CORE;
END PK_PIX;
/

CREATE OR REPLACE PACKAGE PK_BOLETOS AS
    PROCEDURE VALIDAR_CONVENIO_CEDENTE(
        P_CPF_CNPJ_PAGADOR IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE CALCULAR_ENCARGOS_LEGAIS(
        P_VALOR IN NUMBER,
        P_DATA_VENCIMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE GERAR_CODIGO_BARRAS(
        P_VALOR IN NUMBER,
        P_CPF_CNPJ_PAGADOR IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE REGISTRAR_TITULO_CIP(
        P_NOSSO_NUMERO IN VARCHAR2,
        P_VALOR IN NUMBER,
        P_CPF_CNPJ_PAGADOR IN VARCHAR2,
        P_DATA_VENCIMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE BAIXAR_TITULO_PAGAMENTO(
        P_NOSSO_NUMERO IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_BOLETOS;
/

CREATE OR REPLACE PACKAGE BODY PK_BOLETOS AS
    PROCEDURE VALIDAR_CONVENIO_CEDENTE(
        P_CPF_CNPJ_PAGADOR IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Convenio cedente valido';
        P_PAYLOAD_JSON := '{"convenioValido":true}';
    END VALIDAR_CONVENIO_CEDENTE;

    PROCEDURE CALCULAR_ENCARGOS_LEGAIS(
        P_VALOR IN NUMBER,
        P_DATA_VENCIMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_JUROS NUMBER;
        V_MULTA NUMBER;
    BEGIN
        V_JUROS := ROUND(P_VALOR * 0.01, 2);
        V_MULTA := ROUND(P_VALOR * 0.02, 2);

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Encargos legais calculados';
        P_PAYLOAD_JSON := '{"juros":' || V_JUROS || ',"multa":' || V_MULTA || '}';
    END CALCULAR_ENCARGOS_LEGAIS;

    PROCEDURE GERAR_CODIGO_BARRAS(
        P_VALOR IN NUMBER,
        P_CPF_CNPJ_PAGADOR IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_CODIGO VARCHAR2(50);
    BEGIN
        V_CODIGO := '341' || TO_CHAR(SYSDATE, 'YYYYMMDD') || TO_CHAR(ABS(DBMS_RANDOM.RANDOM));

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Codigo de barras gerado';
        P_PAYLOAD_JSON := '{"codigoBarras":"' || V_CODIGO || '"}';
    END GERAR_CODIGO_BARRAS;

    PROCEDURE REGISTRAR_TITULO_CIP(
        P_NOSSO_NUMERO IN VARCHAR2,
        P_VALOR IN NUMBER,
        P_CPF_CNPJ_PAGADOR IN VARCHAR2,
        P_DATA_VENCIMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        INSERT INTO BOLETOS (NOSSO_NUMERO, CPF_CNPJ_PAGADOR, VALOR, DATA_VENCIMENTO, STATUS)
        VALUES (P_NOSSO_NUMERO, P_CPF_CNPJ_PAGADOR, P_VALOR, P_DATA_VENCIMENTO, 'REGISTRADO');

        COMMIT;

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Titulo registrado na CIP';
        P_PAYLOAD_JSON := '{"nossoNumero":"' || P_NOSSO_NUMERO || '","status":"REGISTRADO"}';

        EXCEPTION
            WHEN OTHERS THEN
                ROLLBACK;
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao registrar titulo: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END REGISTRAR_TITULO_CIP;

    PROCEDURE BAIXAR_TITULO_PAGAMENTO(
        P_NOSSO_NUMERO IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        UPDATE BOLETOS SET STATUS = 'BAIXADO'
        WHERE NOSSO_NUMERO = P_NOSSO_NUMERO;

        IF SQL%ROWCOUNT = 0 THEN
            P_RESULTADO_NEGOCIO := 'REPROVADO';
            P_MENSAGEM := 'Titulo nao encontrado';
            P_PAYLOAD_JSON := '{"erro":"Titulo nao encontrado"}';
            RETURN;
        END IF;

        COMMIT;

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Titulo baixado por pagamento';

        EXCEPTION
            WHEN OTHERS THEN
                ROLLBACK;
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao baixar titulo: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END BAIXAR_TITULO_PAGAMENTO;
END PK_BOLETOS;
/

CREATE OR REPLACE PACKAGE PK_CARTAO AS
    PROCEDURE VALIDAR_SOLICITACAO_CARTAO(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE DEFINIR_LIMITE_CREDITO(
        P_COD_CLI IN NUMBER,
        P_LIMITE_DESEJADO IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE VERIFICAR_ADESAO_SERVICOS(
        P_COD_CLI IN NUMBER,
        P_PRODUTO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE EMITIR_CARTAO_VIRTUAL_FISICO(
        P_COD_CLI IN NUMBER,
        P_PRODUTO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE ATIVAR_CARTAO_ADQUIRENTE(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_CARTAO;
/

CREATE OR REPLACE PACKAGE BODY PK_CARTAO AS
    PROCEDURE VALIDAR_SOLICITACAO_CARTAO(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_STATUS VARCHAR2(30);
    BEGIN
        SELECT STATUS_CADASTRAL INTO V_STATUS FROM CLIENTES WHERE COD_CLI = P_COD_CLI;

        IF V_STATUS = 'ATIVO' THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Solicitacao de cartao valida';
        ELSE
            P_RESULTADO_NEGOCIO := 'REPROVADO';
            P_MENSAGEM := 'Cliente com cadastro irregular';
        END IF;

        P_PAYLOAD_JSON := '{"statusCadastral":"' || V_STATUS || '"}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Cliente nao encontrado';
                P_PAYLOAD_JSON := '{"erro":"Cliente nao encontrado"}';
    END VALIDAR_SOLICITACAO_CARTAO;

    PROCEDURE DEFINIR_LIMITE_CREDITO(
        P_COD_CLI IN NUMBER,
        P_LIMITE_DESEJADO IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_RENDA NUMBER;
        V_LIMITE_SUGERIDO NUMBER;
    BEGIN
        SELECT NVL(RENDA_COMPROVADA, 0) INTO V_RENDA FROM CLIENTES WHERE COD_CLI = P_COD_CLI;
        V_LIMITE_SUGERIDO := V_RENDA * 3;

        IF P_LIMITE_DESEJADO <= V_LIMITE_SUGERIDO THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Limite de credito definido';
        ELSE
            P_RESULTADO_NEGOCIO := 'ALERTA';
            P_MENSAGEM := 'Limite desejado acima do sugerido';
        END IF;

        P_PAYLOAD_JSON := '{"limiteSugerido":' || V_LIMITE_SUGERIDO || '}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Cliente nao encontrado';
                P_PAYLOAD_JSON := '{"erro":"Cliente nao encontrado"}';
    END DEFINIR_LIMITE_CREDITO;

    PROCEDURE VERIFICAR_ADESAO_SERVICOS(
        P_COD_CLI IN NUMBER,
        P_PRODUTO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Adesao aos servicos verificada';
        P_PAYLOAD_JSON := '{"adesaoServicos":true}';
    END VERIFICAR_ADESAO_SERVICOS;

    PROCEDURE EMITIR_CARTAO_VIRTUAL_FISICO(
        P_COD_CLI IN NUMBER,
        P_PRODUTO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_NUMERO_CARTAO VARCHAR2(20);
    BEGIN
        V_NUMERO_CARTAO := '4532' || TO_CHAR(ABS(DBMS_RANDOM.RANDOM), 'FM000000000000');

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Cartao emitido com sucesso';
        P_PAYLOAD_JSON := '{"numeroCartao":"' || V_NUMERO_CARTAO || '","tipo":"VIRTUAL_FISICO"}';
    END EMITIR_CARTAO_VIRTUAL_FISICO;

    PROCEDURE ATIVAR_CARTAO_ADQUIRENTE(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Cartao ativado na adquirente';
        P_PAYLOAD_JSON := '{"cartaoAtivado":true}';
    END ATIVAR_CARTAO_ADQUIRENTE;
END PK_CARTAO;
/

CREATE OR REPLACE PACKAGE PK_COMPLIANCE AS
    PROCEDURE MONITORAR_TRANSACOES_SUSPEITAS(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE VALIDAR_ORIGEM_FUNDOS(
        P_COD_CLI IN NUMBER,
        P_MOTIVO_ANALISE IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE ATUALIZAR_CADASTRO_CLIENTE(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE GERAR_COMUNICADO_COAF(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE BLOQUEAR_PREVENTIVO_CONTA(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_COMPLIANCE;
/

CREATE OR REPLACE PACKAGE BODY PK_COMPLIANCE AS
    PROCEDURE MONITORAR_TRANSACOES_SUSPEITAS(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Nenhuma transacao suspeita identificada';
        P_PAYLOAD_JSON := '{"transacoesSuspeitas":0}';
    END MONITORAR_TRANSACOES_SUSPEITAS;

    PROCEDURE VALIDAR_ORIGEM_FUNDOS(
        P_COD_CLI IN NUMBER,
        P_MOTIVO_ANALISE IN VARCHAR2,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Origem dos fundos validada';
        P_PAYLOAD_JSON := '{"origemFundosValidada":true}';
    END VALIDAR_ORIGEM_FUNDOS;

    PROCEDURE ATUALIZAR_CADASTRO_CLIENTE(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        UPDATE CLIENTES SET DATA_CADASTRO = SYSDATE WHERE COD_CLI = P_COD_CLI;
        COMMIT;

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Cadastro atualizado com sucesso';

        EXCEPTION
            WHEN OTHERS THEN
                ROLLBACK;
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao atualizar cadastro: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END ATUALIZAR_CADASTRO_CLIENTE;

    PROCEDURE GERAR_COMUNICADO_COAF(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_PROTOCOLO VARCHAR2(50);
    BEGIN
        V_PROTOCOLO := 'COAF-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || TO_CHAR(ABS(DBMS_RANDOM.RANDOM));

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Comunicado COAF gerado';
        P_PAYLOAD_JSON := '{"protocolo":"' || V_PROTOCOLO || '"}';
    END GERAR_COMUNICADO_COAF;

    PROCEDURE BLOQUEAR_PREVENTIVO_CONTA(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        UPDATE CONTAS SET STATUS = 'BLOQUEADA'
        WHERE COD_CLI = P_COD_CLI;

        COMMIT;

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Conta bloqueada preventivamente';

        EXCEPTION
            WHEN OTHERS THEN
                ROLLBACK;
                P_RESULTADO_NEGOCIO := 'INCONCLUSIVO';
                P_MENSAGEM := 'Erro ao bloquear conta: ' || SQLERRM;
                P_PAYLOAD_JSON := '{"erro":"' || REPLACE(SQLERRM, '"', '''') || '"}';
    END BLOQUEAR_PREVENTIVO_CONTA;
END PK_COMPLIANCE;
/

CREATE OR REPLACE PACKAGE PK_RECUPERACAO AS
    PROCEDURE IDENTIFICAR_VENCIMENTO_ATRASO(
        P_CONTRATO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE CALCULAR_ATUALIZACAO_MONETARIA(
        P_CONTRATO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE VERIFICAR_ACORDO_POSSIVEL(
        P_CONTRATO_ID IN NUMBER,
        P_QTD_PARCELAS_REN IN NUMBER,
        P_PERCENTUAL_DESCONTO IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE REGISTRAR_PROTESTO_CARTORIO(
        P_CONTRATO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE ATUALIZAR_CENTRAL_RISCO(
        P_CONTRATO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_RECUPERACAO;
/

CREATE OR REPLACE PACKAGE BODY PK_RECUPERACAO AS
    PROCEDURE IDENTIFICAR_VENCIMENTO_ATRASO(
        P_CONTRATO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_DIAS_ATRASO NUMBER;
        V_STATUS VARCHAR2(30);
    BEGIN
        SELECT NVL(DIAS_ATRASO, 0), STATUS INTO V_DIAS_ATRASO, V_STATUS
        FROM CONTRATOS WHERE CONTRATO_ID = P_CONTRATO_ID;

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Vencimento identificado';
        P_PAYLOAD_JSON := '{"diasAtraso":' || V_DIAS_ATRASO || ',"statusContrato":"' || V_STATUS || '"}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Contrato nao encontrado';
                P_PAYLOAD_JSON := '{"erro":"Contrato nao encontrado"}';
    END IDENTIFICAR_VENCIMENTO_ATRASO;

    PROCEDURE CALCULAR_ATUALIZACAO_MONETARIA(
        P_CONTRATO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_VALOR_TOTAL NUMBER;
        V_DIAS_ATRASO NUMBER;
        V_ATUALIZADO NUMBER;
    BEGIN
        SELECT VALOR_TOTAL, NVL(DIAS_ATRASO, 0)
        INTO V_VALOR_TOTAL, V_DIAS_ATRASO
        FROM CONTRATOS WHERE CONTRATO_ID = P_CONTRATO_ID;

        V_ATUALIZADO := V_VALOR_TOTAL * POWER(1.01, V_DIAS_ATRASO / 30);

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Atualizacao monetaria calculada';
        P_PAYLOAD_JSON := '{"valorOriginal":' || V_VALOR_TOTAL || ',"valorAtualizado":' || ROUND(V_ATUALIZADO, 2) || '}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Contrato nao encontrado';
                P_PAYLOAD_JSON := '{"erro":"Contrato nao encontrado"}';
    END CALCULAR_ATUALIZACAO_MONETARIA;

    PROCEDURE VERIFICAR_ACORDO_POSSIVEL(
        P_CONTRATO_ID IN NUMBER,
        P_QTD_PARCELAS_REN IN NUMBER,
        P_PERCENTUAL_DESCONTO IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_STATUS VARCHAR2(30);
    BEGIN
        SELECT STATUS INTO V_STATUS FROM CONTRATOS WHERE CONTRATO_ID = P_CONTRATO_ID;

        IF V_STATUS IN ('VENCIDO', 'INADIMPLENTE') THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Acordo de renegociação possivel';
        ELSE
            P_RESULTADO_NEGOCIO := 'ALERTA';
            P_MENSAGEM := 'Contrato nao esta em atraso';
        END IF;

        P_PAYLOAD_JSON := '{"acordoPossivel":true,"parcelasRenegociacao":' || P_QTD_PARCELAS_REN || '}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Contrato nao encontrado';
                P_PAYLOAD_JSON := '{"erro":"Contrato nao encontrado"}';
    END VERIFICAR_ACORDO_POSSIVEL;

    PROCEDURE REGISTRAR_PROTESTO_CARTORIO(
        P_CONTRATO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Protesto registrado em cartorio';
        P_PAYLOAD_JSON := '{"protestoRegistrado":true}';
    END REGISTRAR_PROTESTO_CARTORIO;

    PROCEDURE ATUALIZAR_CENTRAL_RISCO(
        P_CONTRATO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Central de risco atualizada';
        P_PAYLOAD_JSON := '{"centralRiscoAtualizada":true}';
    END ATUALIZAR_CENTRAL_RISCO;
END PK_RECUPERACAO;
/

CREATE OR REPLACE PACKAGE PK_INVESTIMENTOS AS
    PROCEDURE VALIDAR_PERFIL_INVESTIDOR(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE CONSULTAR_DISPONIBILIDADE_PRODUTOS(
        P_PRODUTO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE CALCULAR_RENTABILIDADE_LIQUIDA(
        P_VALOR_APLICACAO IN NUMBER,
        P_PRODUTO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE REGISTRAR_OPERACAO_B3_CETIP(
        P_COD_CLI IN NUMBER,
        P_PRODUTO_ID IN NUMBER,
        P_VALOR_APLICACAO IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE ATUALIZAR_POSICAO_CLIENTE(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_INVESTIMENTOS;
/

CREATE OR REPLACE PACKAGE BODY PK_INVESTIMENTOS AS
    PROCEDURE VALIDAR_PERFIL_INVESTIDOR(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_PERFIL VARCHAR2(30);
    BEGIN
        SELECT NVL(PERFIL_INVESTIDOR, 'NAO_INFORMADO') INTO V_PERFIL
        FROM CLIENTES WHERE COD_CLI = P_COD_CLI;

        IF V_PERFIL != 'NAO_INFORMADO' THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Perfil de investidor valido';
        ELSE
            P_RESULTADO_NEGOCIO := 'ALERTA';
            P_MENSAGEM := 'Perfil de investidor nao informado';
        END IF;

        P_PAYLOAD_JSON := '{"perfilInvestidor":"' || V_PERFIL || '"}';

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                P_RESULTADO_NEGOCIO := 'REPROVADO';
                P_MENSAGEM := 'Cliente nao encontrado';
                P_PAYLOAD_JSON := '{"erro":"Cliente nao encontrado"}';
    END VALIDAR_PERFIL_INVESTIDOR;

    PROCEDURE CONSULTAR_DISPONIBILIDADE_PRODUTOS(
        P_PRODUTO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Produto disponivel para aplicacao';
        P_PAYLOAD_JSON := '{"produtoDisponivel":true,"produtoId":' || P_PRODUTO_ID || '}';
    END CONSULTAR_DISPONIBILIDADE_PRODUTOS;

    PROCEDURE CALCULAR_RENTABILIDADE_LIQUIDA(
        P_VALOR_APLICACAO IN NUMBER,
        P_PRODUTO_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_RENTABILIDADE NUMBER;
    BEGIN
        V_RENTABILIDADE := ROUND(P_VALOR_APLICACAO * 0.005, 2);

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Rentabilidade calculada';
        P_PAYLOAD_JSON := '{"rentabilidadeLiquidaMensal":' || V_RENTABILIDADE || '}';
    END CALCULAR_RENTABILIDADE_LIQUIDA;

    PROCEDURE REGISTRAR_OPERACAO_B3_CETIP(
        P_COD_CLI IN NUMBER,
        P_PRODUTO_ID IN NUMBER,
        P_VALOR_APLICACAO IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Operacao registrada na B3/CETIP';
        P_PAYLOAD_JSON := '{"operacaoRegistrada":true,"codCli":' || P_COD_CLI || '}';
    END REGISTRAR_OPERACAO_B3_CETIP;

    PROCEDURE ATUALIZAR_POSICAO_CLIENTE(
        P_COD_CLI IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Posicao do cliente atualizada';
        P_PAYLOAD_JSON := '{"posicaoAtualizada":true}';
    END ATUALIZAR_POSICAO_CLIENTE;
END PK_INVESTIMENTOS;
/

CREATE OR REPLACE PACKAGE PK_GARANTIAS AS
    PROCEDURE AVALIAR_BEM_GARANTIA(
        P_GARANTIA_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE VALIDAR_ESCRITURA_REGISTRO(
        P_GARANTIA_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE CALCULAR_CET_TAXA_EFETIVA(
        P_VALOR_FINANCIADO IN NUMBER,
        P_RENDA_COMPROVADA IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE VERIFICAR_SEGURO_OBRIGATORIO(
        P_GARANTIA_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE REGISTRAR_ALIENACAO_FIDUCIARIA(
        P_GARANTIA_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_GARANTIAS;
/

CREATE OR REPLACE PACKAGE BODY PK_GARANTIAS AS
    PROCEDURE AVALIAR_BEM_GARANTIA(
        P_GARANTIA_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Bem em garantia avaliado com sucesso';
        P_PAYLOAD_JSON := '{"garantiaId":' || P_GARANTIA_ID || ',"valorAvaliacao":150000}';
    END AVALIAR_BEM_GARANTIA;

    PROCEDURE VALIDAR_ESCRITURA_REGISTRO(
        P_GARANTIA_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Escritura e registro validos';
        P_PAYLOAD_JSON := '{"escrituraValida":true}';
    END VALIDAR_ESCRITURA_REGISTRO;

    PROCEDURE CALCULAR_CET_TAXA_EFETIVA(
        P_VALOR_FINANCIADO IN NUMBER,
        P_RENDA_COMPROVADA IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_CET NUMBER;
    BEGIN
        V_CET := ROUND(P_VALOR_FINANCIADO * 0.001, 2);

        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'CET e taxa efetiva calculados';
        P_PAYLOAD_JSON := '{"cet":' || V_CET || '}';
    END CALCULAR_CET_TAXA_EFETIVA;

    PROCEDURE VERIFICAR_SEGURO_OBRIGATORIO(
        P_GARANTIA_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Seguro obrigatorio ativo';
        P_PAYLOAD_JSON := '{"seguroAtivo":true}';
    END VERIFICAR_SEGURO_OBRIGATORIO;

    PROCEDURE REGISTRAR_ALIENACAO_FIDUCIARIA(
        P_GARANTIA_ID IN NUMBER,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Alienacao fiduciaria registrada';
        P_PAYLOAD_JSON := '{"alienacaoRegistrada":true}';
    END REGISTRAR_ALIENACAO_FIDUCIARIA;
END PK_GARANTIAS;
/

CREATE OR REPLACE PACKAGE PK_FECHAMENTO AS
    PROCEDURE VALIDAR_SALDOS_CAIXA_TERMINAIS(
        P_DATA_PROCESSAMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE CONCILIAR_EXTRATOS_BANCARIOS(
        P_DATA_PROCESSAMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE VERIFICAR_LANCAMENTOS_PENDENTES(
        P_DATA_PROCESSAMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE CALCULAR_PROVISOES_RESERVAS(
        P_DATA_PROCESSAMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
    PROCEDURE FECHAR_CONTABILIDADE_DIA(
        P_DATA_PROCESSAMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    );
END PK_FECHAMENTO;
/

CREATE OR REPLACE PACKAGE BODY PK_FECHAMENTO AS
    PROCEDURE VALIDAR_SALDOS_CAIXA_TERMINAIS(
        P_DATA_PROCESSAMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Saldos de caixa validados';
        P_PAYLOAD_JSON := '{"saldosConferidos":true,"dataProcessamento":"' || TO_CHAR(P_DATA_PROCESSAMENTO, 'YYYY-MM-DD') || '"}';
    END VALIDAR_SALDOS_CAIXA_TERMINAIS;

    PROCEDURE CONCILIAR_EXTRATOS_BANCARIOS(
        P_DATA_PROCESSAMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Extratos bancarios conciliados';
        P_PAYLOAD_JSON := '{"extratosConciliados":true}';
    END CONCILIAR_EXTRATOS_BANCARIOS;

    PROCEDURE VERIFICAR_LANCAMENTOS_PENDENTES(
        P_DATA_PROCESSAMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
        V_PENDENTES NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_PENDENTES FROM OPERACOES_PIX
        WHERE STATUS = 'PENDENTE' AND TRUNC(DATA_CRIACAO) = TRUNC(P_DATA_PROCESSAMENTO);

        IF V_PENDENTES = 0 THEN
            P_RESULTADO_NEGOCIO := 'APROVADO';
            P_MENSAGEM := 'Nenhum lancamento pendente';
        ELSE
            P_RESULTADO_NEGOCIO := 'ALERTA';
            P_MENSAGEM := 'Existem lancamentos pendentes';
        END IF;

        P_PAYLOAD_JSON := '{"lancamentosPendentes":' || V_PENDENTES || '}';
    END VERIFICAR_LANCAMENTOS_PENDENTES;

    PROCEDURE CALCULAR_PROVISOES_RESERVAS(
        P_DATA_PROCESSAMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Provisoes e reservas calculadas';
        P_PAYLOAD_JSON := '{"provisoesCalculadas":true}';
    END CALCULAR_PROVISOES_RESERVAS;

    PROCEDURE FECHAR_CONTABILIDADE_DIA(
        P_DATA_PROCESSAMENTO IN DATE,
        P_RESULTADO_NEGOCIO OUT VARCHAR2,
        P_MENSAGEM OUT VARCHAR2,
        P_PAYLOAD_JSON OUT CLOB
    ) IS
    BEGIN
        P_RESULTADO_NEGOCIO := 'APROVADO';
        P_MENSAGEM := 'Contabilidade do dia fechada';
        P_PAYLOAD_JSON := '{"contabilidadeFechada":true}';
    END FECHAR_CONTABILIDADE_DIA;
END PK_FECHAMENTO;
/
