ALTER SESSION SET CONTAINER = FREEPDB1;

-- Grant para APP_CONSISTENCIA (pode executar tudo)
GRANT EXECUTE ON BANK_CORE.PK_SCORE TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_BACEN TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_RENDA TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_CREDITO TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_PROPOSTA TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_ONBOARDING TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_PIX TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_BOLETOS TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_CARTAO TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_COMPLIANCE TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_RECUPERACAO TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_INVESTIMENTOS TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_GARANTIAS TO APP_CONSISTENCIA;
GRANT EXECUTE ON BANK_CORE.PK_FECHAMENTO TO APP_CONSISTENCIA;

GRANT SELECT, INSERT, UPDATE ON BANK_CORE.RASTRO_GRUPO TO APP_CONSISTENCIA;
GRANT SELECT, INSERT, UPDATE ON BANK_CORE.RASTRO_CONSISTENCIA TO APP_CONSISTENCIA;
GRANT SELECT ON BANK_CORE.CLIENTES TO APP_CONSISTENCIA;
GRANT SELECT ON BANK_CORE.CONTAS TO APP_CONSISTENCIA;
GRANT SELECT ON BANK_CORE.CONTRATOS TO APP_CONSISTENCIA;
GRANT SELECT ON BANK_CORE.CHAVES_PIX TO APP_CONSISTENCIA;
GRANT SELECT, INSERT, UPDATE ON BANK_CORE.PROPOSTAS_CREDITO TO APP_CONSISTENCIA;
GRANT SELECT, INSERT, UPDATE ON BANK_CORE.OPERACOES_PIX TO APP_CONSISTENCIA;
GRANT SELECT, INSERT, UPDATE ON BANK_CORE.BOLETOS TO APP_CONSISTENCIA;

-- Grant para APP_READONLY (apenas leitura)
GRANT EXECUTE ON BANK_CORE.PK_SCORE TO APP_READONLY;
GRANT EXECUTE ON BANK_CORE.PK_BACEN TO APP_READONLY;
GRANT EXECUTE ON BANK_CORE.PK_RENDA TO APP_READONLY;
GRANT EXECUTE ON BANK_CORE.PK_CREDITO TO APP_READONLY;
GRANT SELECT ON BANK_CORE.RASTRO_GRUPO TO APP_READONLY;
GRANT SELECT ON BANK_CORE.RASTRO_CONSISTENCIA TO APP_READONLY;
GRANT SELECT ON BANK_CORE.CLIENTES TO APP_READONLY;
GRANT SELECT ON BANK_CORE.CONTAS TO APP_READONLY;

-- Grant para APP_READWRITE (leitura de tabelas, execucao de todas as procedures)
GRANT EXECUTE ON BANK_CORE.PK_SCORE TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_BACEN TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_RENDA TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_CREDITO TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_PROPOSTA TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_ONBOARDING TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_PIX TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_BOLETOS TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_CARTAO TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_COMPLIANCE TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_RECUPERACAO TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_INVESTIMENTOS TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_GARANTIAS TO APP_READWRITE;
GRANT EXECUTE ON BANK_CORE.PK_FECHAMENTO TO APP_READWRITE;
GRANT SELECT, INSERT, UPDATE ON BANK_CORE.PROPOSTAS_CREDITO TO APP_READWRITE;
GRANT SELECT, INSERT, UPDATE ON BANK_CORE.OPERACOES_PIX TO APP_READWRITE;
GRANT SELECT ON BANK_CORE.RASTRO_GRUPO TO APP_READWRITE;
GRANT SELECT ON BANK_CORE.RASTRO_CONSISTENCIA TO APP_READWRITE;

-- APP_RESTRICTED: sem grants (para gerar ORA-01031)
