ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = BANK_CORE;

-- Clientes
INSERT ALL
    INTO CLIENTES (COD_CLI, CPF_CNPJ, NOME, SCORE_INTERNO, STATUS_CADASTRAL, RENDA_COMPROVADA, PERFIL_INVESTIDOR)
    VALUES (1, '11111111111', 'CLIENTE ALTO SCORE', 850, 'ATIVO', 15000.00, 'MODERADO')
    INTO CLIENTES (COD_CLI, CPF_CNPJ, NOME, SCORE_INTERNO, STATUS_CADASTRAL, RENDA_COMPROVADA, PERFIL_INVESTIDOR)
    VALUES (2, '22222222222', 'CLIENTE BAIXO SCORE', 400, 'ATIVO', 3000.00, 'CONSERVADOR')
    INTO CLIENTES (COD_CLI, CPF_CNPJ, NOME, SCORE_INTERNO, STATUS_CADASTRAL, RENDA_COMPROVADA, PERFIL_INVESTIDOR)
    VALUES (3, '33333333333', 'CLIENTE SEM RENDA', 550, 'PENDENTE', 0, 'NAO_INFORMADO')
    INTO CLIENTES (COD_CLI, CPF_CNPJ, NOME, SCORE_INTERNO, STATUS_CADASTRAL, RENDA_COMPROVADA, PERFIL_INVESTIDOR)
    VALUES (4, '44444444444', 'CLIENTE RESTRITO', 300, 'BLOQUEADO', 1200.00, 'NAO_INFORMADO')
    INTO CLIENTES (COD_CLI, CPF_CNPJ, NOME, SCORE_INTERNO, STATUS_CADASTRAL, RENDA_COMPROVADA, PERFIL_INVESTIDOR)
    VALUES (5, '55555555555', 'CLIENTE NOVO', 700, 'ATIVO', 5000.00, 'AGRESSIVO')
SELECT 1 FROM DUAL;

-- Contas
INSERT ALL
    INTO CONTAS (AGENCIA, CONTA, COD_CLI, SALDO_DISPONIVEL, STATUS, LIMITE_PIX_DIARIO)
    VALUES ('0001', '10000-0', 1, 50000.00, 'ATIVA', 10000.00)
    INTO CONTAS (AGENCIA, CONTA, COD_CLI, SALDO_DISPONIVEL, STATUS, LIMITE_PIX_DIARIO)
    VALUES ('0001', '10001-1', 2, 2000.00, 'ATIVA', 3000.00)
    INTO CONTAS (AGENCIA, CONTA, COD_CLI, SALDO_DISPONIVEL, STATUS, LIMITE_PIX_DIARIO)
    VALUES ('0001', '10002-2', 3, 0, 'PENDENTE', 500.00)
    INTO CONTAS (AGENCIA, CONTA, COD_CLI, SALDO_DISPONIVEL, STATUS, LIMITE_PIX_DIARIO)
    VALUES ('0001', '10003-3', 4, 150.00, 'BLOQUEADA', 100.00)
    INTO CONTAS (AGENCIA, CONTA, COD_CLI, SALDO_DISPONIVEL, STATUS, LIMITE_PIX_DIARIO)
    VALUES ('0002', '20000-0', 5, 10000.00, 'ATIVA', 5000.00)
SELECT 1 FROM DUAL;

-- Contratos
INSERT ALL
    INTO CONTRATOS (CONTRATO_ID, COD_CLI, TIPO_OPERACAO, STATUS, VALOR_TOTAL, QTD_PARCELAS, DIAS_ATRASO)
    VALUES (1, 1, 'EMPRESTIMO_PESSOAL', 'ATIVO', 25000.00, 36, 0)
    INTO CONTRATOS (CONTRATO_ID, COD_CLI, TIPO_OPERACAO, STATUS, VALOR_TOTAL, QTD_PARCELAS, DIAS_ATRASO)
    VALUES (2, 2, 'EMPRESTIMO_PESSOAL', 'ATIVO', 5000.00, 12, 0)
    INTO CONTRATOS (CONTRATO_ID, COD_CLI, TIPO_OPERACAO, STATUS, VALOR_TOTAL, QTD_PARCELAS, DIAS_ATRASO)
    VALUES (3, 3, 'FINANCIAMENTO', 'VENCIDO', 15000.00, 24, 90)
    INTO CONTRATOS (CONTRATO_ID, COD_CLI, TIPO_OPERACAO, STATUS, VALOR_TOTAL, QTD_PARCELAS, DIAS_ATRASO)
    VALUES (4, 4, 'EMPRESTIMO_PESSOAL', 'INADIMPLENTE', 8000.00, 18, 180)
    INTO CONTRATOS (CONTRATO_ID, COD_CLI, TIPO_OPERACAO, STATUS, VALOR_TOTAL, QTD_PARCELAS, DIAS_ATRASO)
    VALUES (5, 5, 'EMPRESTIMO_PESSOAL', 'ATIVO', 10000.00, 24, 0)
SELECT 1 FROM DUAL;

-- Chaves PIX
INSERT ALL
    INTO CHAVES_PIX (CHAVE, TIPO, COD_CLI, STATUS)
    VALUES ('cliente1@email.com', 'EMAIL', 1, 'ATIVA')
    INTO CHAVES_PIX (CHAVE, TIPO, COD_CLI, STATUS)
    VALUES ('11999999999', 'CELULAR', 1, 'ATIVA')
    INTO CHAVES_PIX (CHAVE, TIPO, COD_CLI, STATUS)
    VALUES ('22222222222', 'CPF', 2, 'ATIVA')
    INTO CHAVES_PIX (CHAVE, TIPO, COD_CLI, STATUS)
    VALUES ('cliente5@email.com', 'EMAIL', 5, 'ATIVA')
SELECT 1 FROM DUAL;

-- Propostas de credito
INSERT ALL
    INTO PROPOSTAS_CREDITO (COD_CLI, VALOR_SOLICITADO, QTD_PARCELAS, TAXA_MENSAL, CET, STATUS)
    VALUES (1, 10000.00, 24, 2.5, 3.0, 'APROVADA')
    INTO PROPOSTAS_CREDITO (COD_CLI, VALOR_SOLICITADO, QTD_PARCELAS, TAXA_MENSAL, CET, STATUS)
    VALUES (2, 3000.00, 12, 3.2, 3.84, 'PENDENTE')
SELECT 1 FROM DUAL;

-- Boletos
INSERT ALL
    INTO BOLETOS (NOSSO_NUMERO, CPF_CNPJ_PAGADOR, VALOR, DATA_VENCIMENTO, STATUS)
    VALUES ('BOLETO-001', '11111111111', 1500.00, SYSDATE + 10, 'PENDENTE')
    INTO BOLETOS (NOSSO_NUMERO, CPF_CNPJ_PAGADOR, VALOR, DATA_VENCIMENTO, STATUS)
    VALUES ('BOLETO-002', '22222222222', 850.00, SYSDATE - 5, 'VENCIDO')
    INTO BOLETOS (NOSSO_NUMERO, CPF_CNPJ_PAGADOR, VALOR, DATA_VENCIMENTO, STATUS)
    VALUES ('BOLETO-003', '33333333333', 2200.00, SYSDATE - 30, 'VENCIDO')
SELECT 1 FROM DUAL;

-- Client onboarding digital (adicionados manualmente)
INSERT ALL
    INTO CLIENTES (COD_CLI, CPF_CNPJ, NOME, SCORE_INTERNO, STATUS_CADASTRAL, RENDA_COMPROVADA, PERFIL_INVESTIDOR)
    VALUES (6, '52998224725', 'CLIENTE ONBOARDING TESTE', 750, 'ATIVO', 8000.00, 'MODERADO')
    INTO CLIENTES (COD_CLI, CPF_CNPJ, NOME, SCORE_INTERNO, STATUS_CADASTRAL, RENDA_COMPROVADA, PERFIL_INVESTIDOR)
    VALUES (7, '33673100696', 'CLIENTE ONBOARDING TESTE 2', 650, 'ATIVO', 5000.00, 'CONSERVADOR')
    INTO CLIENTES (COD_CLI, CPF_CNPJ, NOME, SCORE_INTERNO, STATUS_CADASTRAL, RENDA_COMPROVADA, PERFIL_INVESTIDOR)
    VALUES (8, '18181818181', 'CLIENTE ORACLE TEST', 700, 'ATIVO', 6000.00, 'MODERADO')
SELECT 1 FROM DUAL;

COMMIT;
